# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: ktsu.ProjectDirector
PackageVersion: 1.0.1-pre.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- projectdirector
- ProjectDirector
FileExtensions:
- cs
- json
- xml
- config
- txt
ReleaseDate: 2026-02-11
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/ktsu-dev/ProjectDirector/releases/download/v1.0.1-pre.3/ProjectDirector-1.0.1-pre.3-win-arm64.zip
  InstallerSha256: 79656A16AA3FFDAC5906289160BBC8F3538A7C2DBF91891ECE9C925F4E11D294
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ProjectDirector.exe
    PortableCommandAlias: projectdirector
- Architecture: x64
  InstallerUrl: https://github.com/ktsu-dev/ProjectDirector/releases/download/v1.0.1-pre.3/ProjectDirector-1.0.1-pre.3-win-x64.zip
  InstallerSha256: 68698201F1B4C0677E72F136F8E7EE755D373138BAF3D827321D1D5C3F47200A
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ProjectDirector.exe
    PortableCommandAlias: projectdirector
- Architecture: x86
  InstallerUrl: https://github.com/ktsu-dev/ProjectDirector/releases/download/v1.0.1-pre.3/ProjectDirector-1.0.1-pre.3-win-x86.zip
  InstallerSha256: 4C34BAC70833BCAF9A8F2D45A75DF751449DBDC1075CE1032C6D3CF281F57479
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ProjectDirector.exe
    PortableCommandAlias: projectdirector
ManifestType: installer
ManifestVersion: 1.10.0
