# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: ktsu.BuildMonitor
PackageVersion: 1.2.26
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- buildmonitor
- ktsu.BuildMonitor
FileExtensions:
- cs
- json
- xml
- config
- txt
ReleaseDate: 2026-02-06
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/ktsu-dev/BuildMonitor/releases/download/v1.2.26/BuildMonitor-1.2.26-win-x86.zip
  InstallerSha256: AFC52C5A12A125277B3D9F116EF74121F7F0D5DCD66FE8385CF0B85F685AA06D
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BuildMonitor.exe
    PortableCommandAlias: buildmonitor
- Architecture: arm64
  InstallerUrl: https://github.com/ktsu-dev/BuildMonitor/releases/download/v1.2.26/BuildMonitor-1.2.26-win-arm64.zip
  InstallerSha256: 7B8ECDFAC4EE9E2ADBEA71E8DFB81F7D9F3B7A2CFA7F6380D08DE6ADD4056C3F
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BuildMonitor.exe
    PortableCommandAlias: buildmonitor
- Architecture: x64
  InstallerUrl: https://github.com/ktsu-dev/BuildMonitor/releases/download/v1.2.26/BuildMonitor-1.2.26-win-x64.zip
  InstallerSha256: 4DB66CAEF31EC68E94508010798451E50FB7817C1B1521A73141F675D7373137
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ktsu.BuildMonitor.exe
    PortableCommandAlias: buildmonitor
ManifestType: installer
ManifestVersion: 1.10.0
